### ISSUE TITLE
swift 3.0

### ISSUE THREAD

**Issue by jackpaster** [Yalantis/ColorMatchTabs#32] opened 2016-10-06 02:50 UTC
Hello, the swift  3.0 version of colormatchtabs is not working. In Xcode 8 its saying that you need to convert the code to swift 3.0 in edit, convert. Can you please fix it

**Comment by jackpaster** [comment] 2016-10-06 02:51
the colormatchtabs framework is causing an error and Xcode is saying that it needs to be converted to swift 3.0

**Comment by serejahh** [comment] 2016-10-06 05:05
Duplicate of #26

**Closed as completed by serejahh** 2016-10-06 05:05 UTC
